### ISSUE TITLE
[BUG] - odin configure

### ISSUE THREAD

**Issue by sankeyraut** [dream11/odin#163]
**Describe the bug**
While using ODIN for the first time, it prompts to run `odin configure`. However after running ODIN configure , following message is displayed

```
bash-3.2$ odin configure
[ WARNING ] Run, `odin configure` to configure odin
[ ERROR ] Environment variable ODIN_ACCESS_KEY is not set. Please set your access key in ODIN_ACCESS_KEY environment variable
```

**To Reproduce**
1. Install Odin using `brew install dream11/tools/odin`
2. Run `odin create environment --name=demo`
3. You will be displayed message `
```
[ WARNING ] Run, `odin configure` to configure odin
This command is accessed by using one of the subcommands below.

Subcommands:
    env            create an environment
    label          create a label
    service-set    create a service-set
```
4. Run `odin configure` to see the same message

**Expected behavior**
Clear message on how to setup `ODIN_ACCESS_KEY`

**Screenshots**

**Additional context**

**Comment by boppanasusanth** [comment]
https://sporta-technologies-private-limi.gitbook.io/developer-platform/onboard-your-service/configure
